- name: Install required packages
  ansible.builtin.apt:
    cache_valid_time: 3600
    name:
    - jq
    - curl
    - wget
    state: latest

- name: Copy over rustdesk-update
  ansible.builtin.template:
    src: rustdesk-update.j2
    dest: /etc/cron.daily/rustdesk-update
    mode: "755"
