- name: Create Forgejo directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "770"
    owner: 1000
    group: 1000
  loop:
    - "{{ DOCKER_VOLUMES_ROOT }}/forgejo"
    - "{{ DOCKER_VOLUMES_ROOT }}/forgejo/data"

- name: Copy over docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ DOCKER_VOLUMES_ROOT }}/forgejo/docker-compose.yml"
    mode: "770"

- name: Start compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ DOCKER_VOLUMES_ROOT }}/forgejo"
    project_name: forgejo

- name: Cleanup compose file
  ansible.builtin.file:
    path: "{{ DOCKER_VOLUMES_ROOT }}/forgejo/docker-compose.yml"
    state: absent
