{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "github-pat-secret",
    "namespace": "arc-runners"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "github-pat-secret",
        "namespace": "arc-runners"
      },
      "type": "Opaque",
      "immutable": true
    },
    "encryptedData": {
      "github_token": "AgAP9ffpjym57eoK0XCBLQuRAjl5yP1Msxss9NnKZkUVcq/mSkJHrSMPnyF9ocNWtY44PwxkELOZRaQ90sr9H8omaP4PpQaIWznPilKhOnwjbvTiJsO+hrbqz7RmQloCqXBknV9tjDgDY/R/ecu0h9MwdIRt1okuOWbU+GXSGAp172JLXhtRSBhCHwMPOQk/if17JYQebRxtqjOuLOfeEBMbUXLTHiupDu5Jju94jEVTYk2c56RZs7nbK33Kl98aozex3gGiw0H7VUgVEzw6CXb4TOcyd1uTViV37sb3ShPUWAoeaBZwH8xk9CBO7X1pIyVShjyrB2SwSz/6mRaWk1WmislKtoLRPG5OYzPJpIQ0Rc+jJqhk+5g5cJAcPMGpCZ87A8ji0IIwSsyfW0gOURcQg1vx06TEVD930KILkXH1qaQaUWQbljlA5OpYKDhOBifMOkgM1ko4XSK5RNgyet8hZEyQvzrCYrz3IEdxhEYiMys6m8yFXpEkei5qK5dn8P4BxBO14JCcQi0bW8B6m/s05hCDgaE6Wa76hYd5auXxLL/qSqodJBUo86WfaX4iqgiG9MFoGcP+0Bjim8Z3HZuHBln64i3fqYiVZfoKreTIxql+oLz3zMoTDcYtA2C4caQrYxF2LTQC39XU88Y0o3UQ0Je68kNxy9zN7N3P1Un5MZ2I91W9c/cJNUSi2Kts1TDAp/GM2OJLK+48HNe/F+pknq7XR8rtunDTKaJOD6q7PG+aF+Is8OTW"
    }
  }
}
