- name: Create iVentoy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "775"
    group: "1000"
  loop:
    - "{{ DOCKER_VOLUMES_ROOT }}/iventoy/data"
    - "{{ DOCKER_VOLUMES_ROOT }}/iventoy/iso"

- name: Copy over docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ DOCKER_VOLUMES_ROOT }}/iventoy/docker-compose.yml"
    mode: "770"

- name: Start compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ DOCKER_VOLUMES_ROOT }}/iventoy"
    project_name: iventoy

- name: Cleanup compose file
  ansible.builtin.file:
    path: "{{ DOCKER_VOLUMES_ROOT }}/iventoy/docker-compose.yml"
    state: absent
