apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/zabbix

patches:
  - target:
      kind: HTTPRoute
      name: zabbix-httproute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: zabbix.greenappleton.com