- hosts: talos_k8s
  roles:
    - roles/k8s-bootstrap
    - roles/k8s-install-argocd
  vars:
    ARGOCD_SSH_PRIVATE_KEY_B64: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39336438653164666263336331356133633238643363663737393363306635313532343535646536
      6564616566316331626633396438653362626639333230370a623936663535343364356262656635
      39376362316535316561363237373166356662386338613432383134623132333064303466373334
      3630646232343138310a366134376439383862656538376163353038663635316430356334376434
      61353630383864353562666633643532626161386131336631653139383739336165353839343263
      61643765326465396235376331376232363735343732303864353136303238626134393635656664
      36666237333731383430373264373362396464356531663634333830643637343335383736653462
      33376431333538383161313964313862663962343261646432373535633331626635613538393433
      32643937373535323434323862346536383832613363626233303930636466383934643833343739
      61643634373766313736323864373539646563393136663565656266393234346263653333343063
      33396639383566636464666135336336316230646461613864633661656637353262666330316235
      64363334613937333861313165373239356263666230653765636633306539353662306364303162
      64363365656239653938363338376339353031323765623136346339386336626264376164353261
      34323263366366663730393333363132393635643731366435326364346664306130336337313835
      39303934326564633561616335306234323233643538613862313962396330653636343536656336
      34633535316566363636643337353534656232383763663235306639383663313266333838303463
      66383064396265623232633032643438653836323834653130396465393539323163666462656639
      33323035376663366563666565663465623830663536613664326337656436616138316235613539
      66356263343763336666623364663266316635336135626235373730633137363065383139383465
      33656439353638316434306166353938346634396133636666353262326430386139393664623234
      35343833316433623337393333323730643235373034373762373938633330653662343934373665
      35643365313762613036626163623362396666656463636630376132343634613862373763356665
      31386262386337396466623531613965396266353737393737393731366363613061613365653337
      35613830643230313036366637636566373636363933323030663564376561386230323965393063
      35396230656533303766326334653661663262383139393861626438613162616230343431323730
      31363266383032343033326439306462313233363633633763653333626638616565653533613139
      61363031383137393531643430663765306363636632326636383836656337313930653432366436
      39366438336536356339656433343334623933393235663836346661323239393334363538306537
      37363732363738633362636339613830666465346238363031383230336361336633353838316664
      63343564383135313638363865393461356332313636363135383562346163303633383535323636
      66343339343665616438313930643638656539333464383033666163636666613837663938386338
      38666532386637313235636164646263313938316463623935333232383538643539383036643737
      30383034333034336531653539383430373330376563356265363362393664326233636164316334
      37313931323361613764613335623433303636653135383666326539646636643565383232316563
      31363263386130356133316630393064323362303636366538316461323964306334343764666561
      37386664616162313564373337383932343939333330663936393464613635363736663330316535
      65636462633135343639386164626639343163326465356238356566303537393162653465383139
      37316165316666643637313135373338663165366132656435653530666638383063666432666435
      30336130346364623665316238396437666366303133373538626261343032333465303766623032
      38616234303033326134303564623630376166633662353534316634646634613735383265373465
      33356132373065343737643163653639636137326133613238393736336332656165343563646236
      34363238333966303338393561353065343736643435353662323634656231303565336638393433
      37383633626639663036316234613062323766393730323431666533343036303161356165316265
      66376263313637633865343966646565303962303737663938643339613836376164333436386465
      34373137623833306231613331323838343566353766313437656439326236383932363535663334
      37636132336662663934366135356661346535643136353765366561303432336330353664323334
      63346433366533316662356232343531366334626638653166643463383238366632656263646463
      36316363303766643636383639643737653562646334333266396137623636383933633533643735
      30366235633961303235613163383265663032623835666465616531313837333736323162376664
      32316534663963626465623736636138633662616366373533616265343865373134633661303961
      39313962333638663038383435623835323863303930653332313165343864643934386332646165
      31633761653134616461623434643166613030353364393530653466613361346432386165616130
      36373766353036313336373439643364373438623066623434656362353838323064323166333035
      34343162336437636633323039353763333935346334616537633131373162663936373262363934
      37323161613535666266663465373965383366633731393237353362363966343237316434626438
      34343531636639316635646232636537336238643165653937343466303330316164613665646564
      33323331343636656638633161646135366165343830373039363537363337376437633832316164
      30373737613862343132656665333235396332366663373036653538396331663933623431656434
      34346138616363333963323030306664366363663765336266633365656661653332303239386533
      64326632343738333731626138303839326431393364343465333039616538323464346338386663
      33393930633462613236373064333738333166623838303462306163373664363033393938353532
      37393434353732306565616137633965653837366237313964626537643830366265303466623337
      64366137616438313237623035353438316437666437656464376561306261653062656464643339
      38633339333365306535633934343866626661653561303565336138616532343938663932343233
      36656362336639353832613839666363366161323734323335323465613466393437363933616230
      64373338363264643362303835646230643636623431646239643034613530613963653638633063
      62633032326662383965653631656466613434633361623834376631663931373437333530633165
      61343161653031623839393435353130366533633661663135303063383831376439613832343530
      61336164663264343030393230316134336533646266653338323761363962383438383030633135
      64333037396435343761363131626634346162393731326233303066643033613534366634633464
      39623236393233363465353337316362363766366630306665623831333432326134353435373066
      61643064623665396235363362363362393233393664396530323137656637306637323562396162
      63373465303237383265333264343363333432323465616439386338363837383764616431663330
      38666363343034303938346534656433306361663362343330663835316135626433333263323739
      35306438376337663161326533616532316561343239303734333438383732656432306232653139
      34376638376133383936313064353638393130323635333439376263333238393338373264663266
      66613639653430346134616365643134636631346530616165623531623037373266646466646466
      33376666313762366136613531363039353937653339626461386139353961356333646666303439
      66343962623762613838623436646563643830613930303238313964663030326162643761643831
      64643263646231643666613065313536333233646265613330303735376139386164643465636634
      39326334663365663864333133633735393964343264343630633232643730373836343133623862
      63653633306531356263633962393031386164353032353364663763343438376333663834613536
      31396230363966653738363735303663316564333662333233383366356230643132366663633237
      37393961336264323339353135336361626435303038613731653466616230366334643330653830
      64333064633131633635313639353038316239366338323630643636346239663935383764313763
      33623530623235646261373131396536303231383664373934663361393235396465666164333235
      65383737383435616531386236383737613364393334363263303665663037663035356539623937
      32623264373832656165643534363030326330626364393037376131386362323834356334386431
      30336135373538373064383963383433346430336339306662303666636363383838633330336430
      37323961633833393036623466353137346539396536626536636337386263616263303635663639
      66336264303336633262646166636536616331306261616132383834386436663562356534383663
      32656532643839303964353738643231636266653765303937323634633065666131396239333430
      64396261373239356361626336363763643663386535353035376330666464363232363034326238
      31393266363562396134653236323236616339653664663338643662383436303063366465353935
      37656162306631386432356464643861636431383439383132363066383532623537316635396138
      37623964356239303136646639336531353735643138376533393862663133613864376531616563
      34393930386366343835383038343534366364353835623665633263393464363335633234633831
      66636632306434323534626539346564633039663664386333333862656132383965353830616463
      33366365383237353165616330353162663962616333313162316339643836656662303236393130
      31363064373637646365623163383832616535376263636230323466323533326138343230353765
      64393036653836343966663063613730393331353436633038636631373365666336646137316165
      39633166363962663862613538396233646166376464663036643035316331656132653733376234
      39633131363237626662613833656164396234376131646632313862386161646561386336316235
      61636262636461626537613733353766326631626462626464393434323737363531376264343938
      63613238303462353363343433656165346233393531353030316566373338623639373765623433
      35306134386136613062656665333166623435373530623733663262633261613133613434336534
      62353732636139613433313166623463656662383735303361616436623234656338366665636164
      33383937633734306237313363393666643637393066623036303361383164626437326637356433
      35373734303633663837633762366339623037346633376232623635663661646265373233356632
      30666334616630363937363132643664363566653064356636393330336162656463613763366531
      39313430353163316133316566373130306331323832666231353861653839386636306161313265
      62306265313364343561643739366461316432323665376661326538396434626164333563356431
      31636566666537303462623133333631643532313733646533343230616637613136323462363130
      36393533666538666236666564373932313561353636393630663331306363653330626439653638
      61323539303437643137613735633664633933383064373430396339303765646330633665643135
      66393262636462643361373934346565336333393931616335356631623333626261346666343238
      33396665353335373837353431343831303166653063653939356538303264663764383232396135
      30633235393164616232616135303938306539306634623639353264303762323839646434323736
      32383263376638653737373735663536336237356530623031316666663935376638666637643066
      32663833633238313563323465316237383937633131636539616465633161653732303334656433
      36623535356561333566613937353266633639363931346663383138333332343630363731343462
      30636437623038633563363230653161313862313161326537316130336664333338343735646337
      63333838613031383736343034366363373639353136633332353165633062373565326536623239
      34646530323564353562343033363837316165616534633930323531373836303233323439646537
      66343936343538323234613861663731313965646462346261333461666438633832356139626533
      30653937636664393533656433373266373135366132366233303863373465386465616537356136
      36663833646132643765343935356361633139353739613039623532316231316465326265616266
      34393863363166386565363431366536313264653261353461626665333866333662653065356131
      31656233383931663161316239373864383735303930396538386530313862323635383032366266
      65323139393666636435346563396430636663353261623035366261313735666564333964643165
      37646235356665666634333265306662333835323366643339383737626132306131616665373534
      33326635613865343236326634626439313834393339326563633438653839316131373333626265
      37653636366633313161613536613536386137323637663466646334313666343933313162346366
      61323530633530663934616463643539636464393931353634626135366265623730303866333433
      35363537363931383264653466663961303764373135306137666331616133313236313933303434
      33386434373133306461636130386235373335663264363237383235653138353634346335316665
      37323734653634306563306631653430663633363263383839653035366239313365616232366335
      36663262336437643062643966643161666334613131623431326531316532343631653335363363
      35663362626133356130396635346333623633653261353666376638646363373766383936313438
      38376531333130353863663035376635646431636231353938363431343738346139303830373638
      33633261386133663762333535623334343630393138316435613838353234633230336236336138
      61633331323030616434656332646336653963346533613434666463353231653338643839393539
      38633534653836363339383035643465393935376234356166383235383838613938636139633330
      63386633303762633632353561633139666463336266643063643765653638336534646131353335
      36663730336238303732656132353961343433326634653865646630343130643238313431636435
      34623139313965306665633661626566386537323738376433363265303632323038323834386462
      33396334343931653038336232643533313838343132663265383939613039636262323930353735
      62643931323261323239363736626138353838663031323630656331666538396637376561343032
      39636461333362343731316235643934653431353138343630343234323562336138356334336135
      38646331616164333032303566653062623730643432663937363037343932626563353537303364
      39393736663237396237613635643332663833353931663066383039616636613234623263376332
      65353539316366356530663033353934353538646631356430363632386162333664306364386363
      35643332656563363432306131613662333036613763396564343661383065323435323039646636
      35623063636335353330363964393332343465663839323336633634373561303663393266623236
      63323934353534386166363034383262366661346166666534393135653439343861623034323661
      63343135663665303339383364663631363934373735393333623632646634343534316337646632
      37666337613932363237633464376461353864313732656434376665343736666563323836303832
      64363862353234316262373431663331623164393738653230373164656234626365623633346138
      37393461646338343665633030646535663366663161373733356232613862643138623637343936
      64303635303634306162346533383864666362613466616235383032396330666637333035343938
      33663134363562363239646632383637343234383866333865656631336564333166323662666662
      64393230383061303435373535653332356463646662653833366132393462353866616662656230
      61353164323934373334616131626664613861616263303963336638396639383161396238373835
      35366337303965663266336436616464333734343564353237343233336233376666626634613166
      62356534346665666132363433396435323639613461633161336263653737313065353937633737
      31376435373135323061643466366561366130316462616637303062663233633531366233313632
      32306337373461636162303532303262333636353966313161373865306364616131363337363933
      62616135313863373733653332613633613763306265663061363862326264643261313131386465
      37326330383235633336336338363363643365353236643739383232616335313864613264353864
      35323935323462623337663363346133666664333061373261373961396664643333323033326436
      33636333383231323038643662333861313131646234376531613932623533313065616566353539
      62653438633164393539396536613231656530383838643531303036633035336636343535653066
      31646331313061316336373735343730306663666332616162343661353464323232343466616532
      61383066343566663731373165356262613366313165666162363733383331326234343632656263
      38623230396364656363653561666639383037396165633035633437303431386463393933643431
      38353565383564353230353135323266316539306262303534303365626566333432383161623666
      66633037626363623632303336643131343932663562303335313637313735376462
    CLOUDFLARE_API_TOKEN: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65343534306530386664383232366232623438623034353830323638363364306366383034376136
      6531323836353339343237663565333638353733313832650a353937643331663631383466636662
      64386464653066656437363534633762663337306463663464323236306262633932386362653436
      3739353430313035610a353266376430626138323865383238613964353931363664323939323335
      63323865633761383661306264633234616631393162633963626261613063326364356533626563
      3365373335636431646431393837626161373238653037323837
