- hosts: parents-server
  become: yes
  roles:
      - roles/enable-auto-update
      - roles/install-zabbix-agent2
      - roles/install-docker
      - roles/install-smartmontools
      - roles/install-kopia
      - roles/install-python-requirements
      - roles/docker-traefik
      - roles/docker-filebrowser
      - roles/parents-wireguard-to-home
      - roles/parents-docker-wireguard
      - roles/parents-docker-zabbix
      - roles/parents-docker-syncthing
      - roles/parents-kopia
      - roles/cloudflare-ddns
  vars:
        KOPIA_REPO_PASSWORD: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              34336166343433313138663934616139346536613537363434323163356631333166666635663531
              3035343735313939613838366663363030353433376661650a373665313432616564326233303338
              39353439323635663666623330393464653138346362383861306339323433396461306336316563
              3130623837343664390a323763626465653333346635393832323864366139306131363435393236
              35666365386133313430373637363565643239343736326664306435356231636661
        CLOUDFLARE_EMAIL: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              37333066653833326235353639303466346635653538663830383464623161656639336639663365
              3530343932666532333037663965376639363130343631380a353435343935376464646434343163
              63333565393962666132313134336263386134646439306130396634373637313437303766343765
              6461653734633234610a653765386666316639303664373866323732636433363837323936313163
              62663265663538376430366434623165306361353136613062653465356239646265
        CLOUDFLARE_DNS_API_TOKEN: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              64333238383931383139326661316232366331353466666531373631326137613663373365306535
              3662306637356532373834383462326331653965633061390a663738636336323866623433623666
              64623834353564306536336465323262623131356231383332636661666339306133353862386438
              6638646262613562310a363537623439356463356538656665383363376261336565333939356233
              39663237663430623939323530653338653232313761616339666236663933346639613137333861
              6132346435313034346431633865303666303635303765643534
        FILEBROWSER_DNS_NAME: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              35396330393932343764303932336339353335326665303963313239346632663732323730376365
              6437323438393031366336323162386462346332613163390a313636363262323264333364633561
              32383231626434663338353961613666666533643561366132356262656263306535633132363963
              3731326662396532660a646636323763653865653930373562623132643865616637346163636561
              65323436363263373330613961323661636132633535393263633266623035323231
        WIREGUARD_URL: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              65396630396165313133353861356437626133626461336135306339363465636637613663663464
              6462363930633936353838643866393565386465383238390a613663616631366530616663653231
              62343266316335316465366137393464346439383833346136383333663963643866623832313264
              3635353966393633660a336366306232326132613031316161316136363930323536323535393333
              35323030613864383230323733373362353762353333353164353264343833353330
        CLOUDFLARE_API_TOKEN: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              30646634363738653263353062363635626361323133386561616634353537636238393238323433
              3463336430333737333866343366373764333532383534660a366363643338613566666333393033
              63626631646264616533373161316564363363353261353861666664613563643030303933636531
              3938643161633630340a376363383166313263343566636331613963356236653839386535313065
              31376565356663326434303532356639323431333731326539613161316235343166383630366533
              3861313431313764613866313035656163343930353234643130
        CLOUDFLARE_ZONE_ID: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              33656638333163663834306338643931323066366133356364343362643935353539363731373536
              3637333637616238386262623362643037666336626462350a316330616536623836383261333532
              61386337366163313564346232643564653035323632383734666534656433613465663962356237
              6333643038346466330a333934356466353064346438373461313261386334656434303063316165
              38623738346664653866396436326533663235303065333965323336326532346233383937383062
              3161316463366132666535333938613737336464383031393933
        CLOUDFLARE_DNS_RECORD_ID_1: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              63373732363364313566323932326262323737656433643835313962333364313838373563383062
              6462333939363263623635393338653330363233366561340a373030376238393535343161363533
              34646330616261646335636436323138356238353164343965663065373364366431396431656338
              6638643039633338660a643863313033636261326531333635366136336639663865663134633232
              37653234633935633935653761376234373830666637313331643534343238646331666461316537
              6164343532383965353838633661343433326364633362623562
        CLOUDFLARE_DNS_FQDN_1: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              35396330393932343764303932336339353335326665303963313239346632663732323730376365
              6437323438393031366336323162386462346332613163390a313636363262323264333364633561
              32383231626434663338353961613666666533643561366132356262656263306535633132363963
              3731326662396532660a646636323763653865653930373562623132643865616637346163636561
              65323436363263373330613961323661636132633535393263633266623035323231
        CLOUDFLARE_DNS_RECORD_ID_2: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              34653034616533323436303935373935336633396362356362366134353061386132633764353037
              3432656538616262633133303434356333383439356132390a383533383730346133623632636263
              61613661616435303862643234303863386263633639386165616630623239383230633431613464
              3466386338386233320a353333376334343964663030653032353933386466343235333265316630
              61653831626132373336643738626230396365653338316131663964336435323030353664643737
              3832373138656564343539633739613738666466306364663536
        CLOUDFLARE_DNS_FQDN_2: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              65396630396165313133353861356437626133626461336135306339363465636637613663663464
              6462363930633936353838643866393565386465383238390a613663616631366530616663653231
              62343266316335316465366137393464346439383833346136383333663963643866623832313264
              3635353966393633660a336366306232326132613031316161316136363930323536323535393333
              35323030613864383230323733373362353762353333353164353264343833353330
        WG_PRIV_KEY: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              33336531326161316632353937666365623839343564636431653532626136373338623534336337
              3538623762656639383235616533626465396562386433320a326261353364396339356538356266
              30323938323339626139663634643535633964653334636231653262643132353565663462356264
              6339383532653336330a633335356265376138626563353735316134643536666261623965376535
              36643062666262323361666364316436363665626166363433613865356565613339636563376330
              6161373531613939363237636335313635616362346531306162
        WG_PRE_SHARED_KEY: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              66646466336333633363613038326639656234626335376132333431396463633530333632306665
              6634653535326337666133303636373864383766336239630a316261313563646163346637616432
              64306136333533346538353462376432356337633961343534386333653865616632346361623938
              6364396166353461300a363163643532393738326465393861356434366139313036333937333666
              33366238343363383131303364663133653036626238306163656130316338376163653164393138
              3933623163373238663238393965333035333132613165643136
