- hosts: truenas
  become: yes
  roles:
    - roles/get-nas-files-list
    - roles/get-ups-status
    - roles/nas-cron-config-backup
    - roles/nas-cron-opnsense-backup
    - roles/nas-cron-speedtest
    - roles/nas-cron-docker-maintenance
    - roles/docker-traefik
    - roles/docker-filebrowser
    - roles/docker-frigate
    - roles/docker-grafana
    - roles/docker-forgejo
    - roles/docker-home-assistant
    - roles/docker-loki
    - roles/docker-alloy
    - roles/docker-immich
    - roles/docker-unifi
    - roles/docker-arr
    - roles/docker-tdarr
    - roles/docker-nas-syncthing
    - roles/docker-nas-zabbix-agent
    - roles/docker-zabbix-pgsql-timescaledb
    - roles/docker-iventoy
  vars:
    DOCKER_VOLUMES_ROOT: /mnt/ssd/docker
    DOWNLOADS_FOLDER_PATH: /mnt/hdd/downloads
    TV_FOLDER_PATH: /mnt/hdd/media/tv
    MOVIES_FOLDER_PATH: /mnt/hdd/media/films
    SEQ_GELF_IP: 10.10.3.2
    CCTV_FQDN: cctv.greenappleton.com
    FILEBROWSER_DNS_NAME: filebrowser.greenappleton.com
    FILEBROWSER_SHARE_ROOT: /mnt/hdd/downloads
    SEQ_DOMAIN: seq.greenappleton.com
    SONARR_API_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64303963636130326561373036616563636561386631633137646165383832623262623136303938
      3961343933306636643065316463353365336132356433630a666539373663383139623237353933
      39643936333563366664336339346663356337323235616532333739326334396236646335646634
      3062303762346663610a656435646633333839313439343536353637623232636134323939356335
      33326330653862316138333963333230376538373834313330346631353665313332353731663337
      3065373739376438323930366662643538333339633139396136
    RADARR_API_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38613432353064373639666639646162333432623966643739626635386263623961313431653762
      3635356665643137393737613362346364646565616235660a653762643366626437326439333738
      31343031336361333436363137326137353836613363633335616539323938353931656636316337
      3131323330636262360a303439393537303437653037643030313736396131633139303763346439
      38373235336331623364626136646438393335376530356636333264303164313933633864323964
      3838386566616539306561336566626533656436653862666161
    ARR_READER_DISCORD_WEBHOOK_URL: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38356636333833356634343431373237383135643365626161316433376264623335323864633131
      6634343361343766613830386637653865326265393430630a343666336462663262636238353839
      62303438356238663065306533653666383064393666376537336466313932653333346562616330
      3039343834613139330a393465343330343338326135323737356532376131326230633538656537
      32303430303266633636623139393362663137363434323464656330653737363737316266353062
      34356130393232623934636561343930346236333463666466613731336535333334316565626562
      36313066343663346563626463616538396535663264623866316132633339303036626664623838
      65393064316639393163386665636563393831336239616264333064313834613934373738613838
      32306630376633343833343263393864643761373437303737353633356334366235666163363532
      3565333066356163323835643166366233316462313038373039
    CLOUDFLARE_EMAIL: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37333066653833326235353639303466346635653538663830383464623161656639336639663365
      3530343932666532333037663965376639363130343631380a353435343935376464646434343163
      63333565393962666132313134336263386134646439306130396634373637313437303766343765
      6461653734633234610a653765386666316639303664373866323732636433363837323936313163
      62663265663538376430366434623165306361353136613062653465356239646265
    CLOUDFLARE_DNS_API_TOKEN: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34383730633432303539366538666130373238306233636138626338343761363732633263616463
      3530396666653730393338613364663532363263396436330a623732356664343964623737363163
      36316432616165383263333661613236356465336136663031323261333361353535353033643862
      3631373166326335340a633033393338663533653166653364663134376462333532663032366566
      63343363306632633063653464343636643433663661333837316564336439343937336639326637
      3462356430653331636639383164653338333834353139343833
    FRIGATE_C1_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61316664646435373033313063663761356533333439356632636136626164653262653634313233
      3638326664613534333761373864383336666538316631350a303334353266633666373939346331
      39303832323334623338383632626161333465653864386136333831366363613661343063376338
      3632316165613536330a663365396261303637396331666535323761623330613630633836663361
      66643262616634656466346362383864313664303835346364656139636465653265
    FRIGATE_C2_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66616464303031373061633233363463613237396261633563306136333531393931316637363961
      3138663339323166643032656263383130376439383835630a383136396439363966306537653830
      37303563623037666538666636636433643938373431346138633830663937653732623061613131
      6533373865333763650a346638343264323061336138353939363235316562306535386530646365
      39346439653338323231353132333566396638336361636164663738646164346331
    FRIGATE_C3_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62326432313365633864366661333861663633396638633961306665346334313931616431643264
      3533363231636431623435303561623333383634653365650a373130356233663937316362306337
      33393138313934653462396164333731386261313366373834366334376463343361376638303536
      3434393332373963360a313232623130353030666537313336323635626435373839613135636263
      61623730633439333436663935396335316635663935303532303234653239316462
    FRIGATE_C4_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37373166396665353237383430373563323532663634306461343965353266393933383939366130
      3665666233383866656365633635333466363861616638320a613433333630343739393430313765
      63633363386337353339386531613839656466323866313338386437346233643563623233666261
      6438666531316433640a393838656563326438323638363961363830303664653261323137353033
      63613135666635346464643635306434373631366534333236636435363338613736
    SEQ_ADMIN_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63653630663464333036346232383764666363616566353137666635386136643065663165666438
      6362343236353638326539393965353830396138343331350a333531356636613439363234396665
      30383639353832653562333363383637306161333734306430626564613235303630313064333566
      3762653434383830630a663461653237626163646266653038333736643763383366646562323535
      36366562326433313836303635383965343830633337336433366132666466313937
    SEQ_SYSLOG_API_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61633937656236313031666337383834663135613437613163623461326566393034653139626334
      6431326465383638646330333161386365623264653033620a666265373461363037316264323764
      64663039623737343565306661343638353764646164313337363233653331663031616436646332
      6133336530666531630a613439353135393033343437356135376635626133303937353335616135
      37363365373430646235633164383264643661383165646135613665356137386134
    SEQ_GELF_API_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35376330323637376461303730653266626366626432663435376530623537333363313135316530
      3330343965623864613366363334626661383030633737300a666639626464336333343265313865
      62303837393531626162633664316464363434396137333433306230663066663862613031643537
      3436333832303833300a396536326130353930353337303333336666326634393364653337636232
      39323932323638393233313966303636373931333964326662396163316336383136
    IMMICH_DB_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65343363353635303464386138383938646336343238313430333734613938313361343733656665
      6638396136336666636337333436663163653266353837350a383235616462666239313766653035
      65333535376264666562383830636133616532646237306565613235626130313830386663376334
      3137333365336135620a363932643461383365653065376430663438353962666262383662346166
      33376430373766616531343462626134303734653263356339636332306132383238
    TRANSMISSION_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35373462326462373338653632613535663233393236616461633239663866323364653434383535
      3265353166346162313938646262643837663266663430360a633530353532363534666332343862
      62653637613865316338346532626264346266323862376432663437333033323532343465323432
      3666643732336233390a666361616266663362356632656439303930343532356138613133363638
      62613865623734376537646166383232326336303965613730396233636436336232
    GLUETUN_WIREGUARD_PRIVATE_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38656364623135333738663837323733393036613766646232616439623333306639383932346564
      3463303339666165663366353438306535383339613836340a363964393736353539343961623035
      35343236303662656463303765323236343835633936383333393532323566353535313466383531
      3635656365366637630a363563383337353532373234386433356236383362306232626565316366
      38653638633762373035323366346538633835633734653830663837393961663664336363393262
      6138666466366264636230653233663037343838303437323264
    GLUETUN_WIREGUARD_ADDRESSES: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      32333933316437663362393033363365653261363137393162376136306138323264363233393366
      3566646561386362623561386533643438313537326533330a633830623034353633663137306262
      61623137623137383162613339316637373930363937663130636232643263643662306137623937
      3061653636393030360a353236656434313539323565343536633337616165316166383238333066
      3339
    GLUETUN_SERVER_CITIES: Amsterdam
    TRUENAS_BACKUP_API_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34633130393661616335396565613234326339626535316532373362623363656562323961343165
      6635383463636134313939623663663062303665333733300a636235666538353266316236386463
      65643261346463363166343264616333353535303637336464343762666437626431626264333139
      6537393361336632380a666165393531356563343462323039613735613831366364633162623538
      66653335663836353730303639613932313732626233336430316431326364303236396430356562
      66383265663162656364303332376538323961323061306637616463386438613233323936333537
      30623534323434336565623830633339313864323762633065643832303664326537646662613065
      38363234333137316535
    TRUENAS_BACKUP_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37613264646536623462636461663032336663613834383535633564346433306463393634663665
      6362393763623634316438356463393931646231326133390a306666353961666463386164643038
      62313562623831313330393139393533653662376331646162393064663732383133366331613136
      6137326530383034660a363464383964373837313331376661626235363737363065613564366236
      34316562356331353330306363636234306637393631373365326261663866653439
    OPNSENSE_BACKUP_API_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33316536643130643766623632376666376561646535346437626461333532343539303637366234
      3933316531326336396663346437363162396234336636380a363339666162303232393639366136
      35383133386161386332373262616166343239643132653635333530643065383831653636346634
      3636346430373035380a373232393637323764383939313261633132643233623536636232663762
      65333562323630633332343034313633643631313264353164373364623832623736646366323631
      64323838336435343839366337646462636263333462656638623134313436323139326433636232
      37663734366333363137636633623136373131636639306138383837336661303964313562356239
      39643965356261333436353331653161316661363039386133386166393632363361613635313834
      3137
    OPNSENSE_BACKUP_API_SECRET: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38336264376335616232663534666332373938633338616533396137353666383931383535386563
      6432373166313662643336373132636132633533653365330a616632383630613465663261316531
      64396664636462626162336631333634356530363539373736366638646430653838613965633766
      6335353761373536350a383036613665383431663138323466383234316136393465396661363434
      64613034373065666664663866633331666265616666356630333961636237386463656632363430
      35343733643364346635666561373232353763313631656566383265336364643530353263616534
      37353264653132376331663635386166353663333338373239343436616563653731343636653731
      37373166323937333936343662373230616536653837303239383831316632623962373737383539
      3662
    OPNSENSE_BACKUP_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37366462363462353639373333353532343065646261663530656461373563333761643763333734
      6166663264336539353063363963383630363032393963320a656634646439373031393437333137
      35396631663335653332623431666466356461623039663339636561653335633434383465363236
      6364326464313036320a393730356433646161623064646138323966343664356530366461666432
      61643735653364336264623465326337613334366136323261396561396265653932
    TDARR_API_KEY: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38653831343765666462616339306665393336383962323531386637373438363031313863393432
      3565613331623463323964633839393064366233363431370a653363613330363536303139393638
      62653065326332616538356131366538613164393765346163303433393565366665383632633134
      3765363730623537640a653463613963623739393465336436666537663331313637333433376632
      3362
