- hosts: proxmox_hosts
  become: yes
  serial: 1 # Run 1 host at a time
  roles:
    - roles/install-proxmox-patches
    
- hosts: dns_servers
  become: yes
  roles:
    - roles/set-pihole-dns
    - roles/set-pihole-hosts