- hosts: forgejo-runner
  become: yes
  roles:
    - roles/enable-auto-update
    - roles/install-docker
    - roles/docker-forgejo-runner
    - roles/install-zabbix-agent2
    - roles/install-alloy-forgejo-runner
  vars:
    FORGEJO_RUNNER_TOKEN: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39353932333064373862383937363838363634306466373164343837373931333534656666393830
      3564666334616537613935643665313638323566363266340a343032666336613438323131656531
      65396237643334333133396262303264333530323266626530316561333132653766663662356265
      3765396461306561660a653930353137623261396133393038373661633035383036353262323635
      31393731646631616537623437356632366238333561656535613235323830626263393863383038
      6130366233363763333138613437306338303936336233356231
