- hosts: chat.greenappleton.com
  become: yes
  roles:
    - roles/enable-auto-update
    - roles/oci-install-zabbix-agent2
    - roles/install-docker
    - roles/docker-traefik
    - roles/docker-haven
    - roles/docker-filebrowser
  vars:
    TRAEFIK_ACME_CHALLENGE: tls
    TRAEFIK_CERT_RESOLVER_NAME: letsencrypt
    FILEBROWSER_DNS_NAME: download.greenappleton.com
    TURN_SECRET: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63383963326530636239343230303931326238653031313265623736343132636232383331373333
      6561636638366633316663346334373863336637386436380a366331373433326361366563333436
      30656564303233646666663632366539353731633438323762663865393735323031343030376338
      3666373234306535660a656162373332383631626439376139373566313832346132363931363133
      39346465373732346435313938373966376435623239343733313539376537356135
    ZABBIX_PSK: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36346365336436353563323665646438336439373264356432396535633862393932316136653965
      3532633437333533326530363830363465623134363837360a336436376135626265346331363336
      62613139623731303430373236383236353531633634633832626439623164643431356436373437
      3438616564373663330a356330303362396433386165666237393264633435623261366338613063
      37383662306231393161323935323433336437333136363430343437306230306332613230393866
      32313966386539333637376136633366663062653537373237653263646332643530643532303837
      31653839613933346239383062323031613264366463376263613134326664303661343432303731
      34383033333839623062
