- name: Create Grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "770"
    owner: "472"
    group: "472"
  loop:
    - "{{ DOCKER_VOLUMES_ROOT }}/grafana"
    - "{{ DOCKER_VOLUMES_ROOT }}/grafana/data"

- name: Copy over docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ DOCKER_VOLUMES_ROOT }}/grafana/docker-compose.yml"
    mode: "770"

- name: Start compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ DOCKER_VOLUMES_ROOT }}/grafana"
    project_name: grafana

- name: Cleanup compose file
  ansible.builtin.file:
    path: "{{ DOCKER_VOLUMES_ROOT }}/grafana/docker-compose.yml"
    state: absent
