apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-db
  labels:
    app: zabbix-db
spec:
  selector:
    matchLabels:
      app: zabbix-db
  replicas: 0
  template:
    metadata:
      labels:
        app: zabbix-db
    spec:
      nodeSelector:
        zabbixdb: allowed
      volumes:
        - name: zabbix-db
          nfs:
            path: /mnt/ssd/k8s/zabbix/zabbix-db/mariadb
            server: 10.10.3.2

      restartPolicy: Always
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: zabbix-db
          image: mariadb:11.5
          resources:
            requests:
              cpu: "1"
              memory: 2G
            limits:
              cpu: "1"
              memory: 2G

          command:
            - mariadbd
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_bin
            - --default-authentication-plugin=mysql_native_password

          env:
            - name: MYSQL_USER
              value: zabbix
            - name: MYSQL_PASSWORD
              value: zabbix
            - name: MYSQL_ROOT_PASSWORD
              value: zabbix

          ports:
            - containerPort: 3306
              name: zabbix-db

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: zabbix-db

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  labels:
    app: zabbix-db
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.3.6
spec:
  type: LoadBalancer
  ports:
    - name: zabbix-db
      port: 3306
      targetPort: 3306
  selector:
    app: zabbix-db
